### PR TITLE
 Setting the correct value to move the plugin into the WordPress codebas...

### PR DESCRIPTION
**Pull request by blobaugh**
...e

### CODE REVIEW

**Comment by tierra** [comment]
Local git clones use hardlinks to HEAD refs, and are actually extremely fast and efficient.

Does this fail to work for you? What error are you running into?

**Comment by ntwb** [comment]
```
$ git clone . "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
Cloning into '/tmp/wordpress/src/wp-content/plugins/bbpress'...
fatal: attempt to fetch/clone from a shallow repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
The command "git clone . "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"" failed and exited with 128 during before_script.
```

This is because when Travis clones the `.` repo it creates a `shallow` repo due to `--depth=50`
`git clone --depth=50 --branch=master git://github.com/bbpress/bbpress.git bbpress/bbpress`

`git clone` docs:

> --depth <depth>
> Create a shallow clone with a history truncated to the specified number of revisions. A shallow repository has a number of limitations (you cannot clone or fetch from it, nor push from nor into it), but is adequate if you are only interested in the recent history of a large project with a long history, and would want to send in fixes as patches.

I am using a workaround similar to @blobaugh patch at the moment to move the repo
`- mv $TRAVIS_BUILD_DIR /tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG`

**Comment by tierra** [comment]
Thanks for explaining, I'll merge this in later.

**Comment by ntwb** [comment]
Nice, the shallow clone of WordPress makes sense, implementing that myself :+1:

**Comment by tierra** [comment]
Yeah, that shaved about 5 seconds off the test runs, and also cut the download down from about 65MB to 8MB.

**Pull request closed without merging**
